### ISSUE TITLE
No audio playing as TTS fails to initialize?

### ISSUE THREAD

**Issue by farazk86** [dlutton/flutter_tts#138]
## 💬 Questions and Help
Hi, 

I'm trying to run ``flutter_tts`` to speak a simple string, I followed the install guide and also the readme.md on how to use it. But when I call the ``speak()`` function I get no output, no sound at all.

When I checked logcat, I have the following error:

`E/TTS: Failed to initialize TextToSpeech`

I checked that TTS engine is installed on the phone by going into settings and running the ``Text-To-Speech`` output. The test output plays without any problems. But from app it fails to initialize.

Below is the relevant code from my app: (this is within a stateful widget)

```
import 'package:flutter_tts/flutter_tts.dart';
FlutterTts _flutterTts;
bool isPlaying = false;

@override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.initialText);    // widget. gives access to all variables the stateful widget has acces to
    _flutterTts = FlutterTts();
    _flutterTts.setStartHandler(() {
      setState(() {
        isPlaying = true;
      });
    });
    _flutterTts.setCompletionHandler(() {
      setState(() {
        isPlaying = false;
      });
    });
    _flutterTts.setErrorHandler((err) {
      setState(() {
        print("error occurred: " + err);
        isPlaying = false;
      });
    });
  }

  @override
  void dispose() {
    super.dispose();
    _flutterTts.stop();
  }

  Future _speak(String text) async {
    await _flutterTts.setLanguage("en-US");
    await _flutterTts.setVolume(1.0);
    await _flutterTts.speak(text);
    if (text != null && text.isNotEmpty) {
      var result = await _flutterTts.speak(text);
      print(result);
      if (result == 1)
        setState(() {
          isPlaying = true;
        });
    }
  }

...
...
...
IconButton(
                  iconSize: 34.0,
                  icon: Icon(Icons.play_arrow),
                  onPressed: () {
                    _speak(_controller.text);
                   
                  },
                ),
```

I searched for this error, but apparently no one else has this problem.

I restarted my phone, restarted Android Studio, still no luck :(

Thanks

**Comment by dlutton** [comment]
what device and api level are you testing on?

**Comment by farazk86** [comment]
> what device and api level are you testing on?

Pixel 3a API 30

**Comment by farazk86** [comment]
@dlutton Here is the logcat output, if this helps in any way.

```
2020-07-15 20:23:52.085 I/yustaz.easy_oc: Not late-enabling -Xcheck:jni (already on)
2020-07-15 20:23:52.097 I/yustaz.easy_oc: Unquickening 12 vdex files!
2020-07-15 20:23:52.098 W/yustaz.easy_oc: Unexpected CPU variant for X86 using defaults: x86
2020-07-15 20:23:52.228 D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-07-15 20:23:52.229 D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-07-15 20:23:52.347 I/FirebaseInitProvider: FirebaseApp initialization successful
2020-07-15 20:23:52.401 I/ResourceExtractor: Found extracted resources res_timestamp-1-1594775981516
2020-07-15 20:23:52.463 D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2020-07-15 20:23:52.489 D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2020-07-15 20:23:52.493 D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2020-07-15 20:23:52.579 D/HostConnection: HostConnection::get() New Host Connection established 0xf6310870, tid 8763
2020-07-15 20:23:52.584 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2020-07-15 20:23:52.606 D/EGL_emulation: eglCreateContext: 0xf6120220: maj 2 min 0 rcv 2
2020-07-15 20:23:52.610 D/HostConnection: HostConnection::get() New Host Connection established 0xf6310750, tid 8799
2020-07-15 20:23:52.615 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2020-07-15 20:23:52.616 D/EGL_emulation: eglMakeCurrent: 0xf6120220: ver 2 0 (tinfo 0xf6479bf0) (first time)
2020-07-15 20:23:52.752 I/flutter: Observatory listening on http://127.0.0.1:42529/t25DJ9bDt9g=/
2020-07-15 20:23:52.779 I/FA: App measurement initialized, version: 21028
2020-07-15 20:23:52.779 I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2020-07-15 20:23:52.780 I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.lewanayustaz.easy_ocr
2020-07-15 20:23:52.831 E/TTS: Failed to initialize TextToSpeech
2020-07-15 20:23:52.878 W/yustaz.easy_oc: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
2020-07-15 20:23:52.879 W/yustaz.easy_oc: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
2020-07-15 20:23:52.879 W/yustaz.easy_oc: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
2020-07-15 20:23:52.880 W/yustaz.easy_oc: Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
2020-07-15 20:23:52.913 I/FA: Tag Manager is not found and thus will not be used
2020-07-15 20:23:52.941 D/HostConnection: HostConnection::get() New Host Connection established 0xf6316210, tid 8794
2020-07-15 20:23:52.947 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2020-07-15 20:23:52.947 W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2020-07-15 20:23:52.962 D/EGL_emulation: eglCreateContext: 0xf6102f50: maj 2 min 0 rcv 2
2020-07-15 20:23:52.967 D/EGL_emulation: eglMakeCurrent: 0xf6102f50: ver 2 0 (tinfo 0xf647d950) (first time)
2020-07-15 20:23:52.972 D/HostConnection: HostConnection::get() New Host Connection established 0xf6316cf0, tid 8798
2020-07-15 20:23:52.979 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2020-07-15 20:23:52.996 D/EGL_emulation: eglCreateContext: 0xf612bcf0: maj 2 min 0 rcv 2
2020-07-15 20:23:53.011 I/Gralloc4: mapper 4.x is not supported
2020-07-15 20:23:53.019 D/HostConnection: createUnique: call
2020-07-15 20:23:53.020 D/HostConnection: HostConnection::get() New Host Connection established 0xf6315b50, tid 8794
2020-07-15 20:23:53.020 D/goldfish-address-space: allocate: Ask for block of size 0x100
2020-07-15 20:23:53.020 D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3fc6b2000 size 0x2000
2020-07-15 20:23:53.032 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2020-07-15 20:23:53.037 D/EGL_emulation: eglMakeCurrent: 0xf612bcf0: ver 2 0 (tinfo 0xf647e330) (first time)
2020-07-15 20:23:54.932 I/yustaz.easy_oc: Waiting for a blocking GC ProfileSaver
```

Thanks

**Comment by farazk86** [comment]
Hi, so I managed to fix this. I still get the same error now but at least the text to speech is working and the ``speak`` function says any string passed to it.

I still get these messages in logcat, but works as intended.

```
2020-07-16 00:10:29.353 4133-4133/? E/TTS: Failed to initialize TextToSpeech
2020-07-16 00:15:05.172 4417-4417/? E/TTS: Failed to initialize TextToSpeech
2020-07-16 00:16:18.524 4619-4619/? E/TTS: Failed to initialize TextToSpeech
2020-07-16 00:19:26.095 5257-5288/? E/TTS.VoiceDataDownloader: Failed to download default voice
    java.util.concurrent.CancellationException: Task was cancelled.
        at czy.b(PG:132)
        at czy.get(PG:82)
        at dbr.a(PG:11)
        at dbb.run(PG:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-07-16 00:26:40.952 5257-5530/? E/TTS.LocalSynthesizer: synthesizeWithoutLoadingVoice() failed
2020-07-16 00:26:54.696 5257-5530/? E/TTS.LocalSynthesizer: synthesizeWithoutLoadingVoice() failed
```

This is what I did, I right clicked on ``build.gradle`` located in ``project_name\android\build.gradle``  and selected import gradle project.

after an import close android studio and re open. The sdk field will be empty in ``File > Project Structure > Project`` so select your sdk from there again (which was API 30 in my case), 

let it do the configs and imports and then run app again. The text to speech works :)
