### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by SandroMaglione** [dlutton/flutter_tts#143]
## 🐛 Bug Report
Sometimes when calling the `speak` method there is an error in `FlutterTtsPlugin.java` which causes the speak to be delayed.
This bug happens on Android, SDK < 26. I report the error here below:
```
D/TTS     ( 6391): Utterance ID has started: SIL_a32e439d-a488-4c26-9d9d-5e0019fb5cb8
W/Binder  ( 6391): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 6391): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/Binder  ( 6391): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$1.onStart(FlutterTtsPlugin.java:82)
W/Binder  ( 6391): 	at android.speech.tts.TextToSpeech$Connection$1.onStart(TextToSpeech.java:2130)
W/Binder  ( 6391): 	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:55)
W/Binder  ( 6391): 	at android.os.Binder.execTransact(Binder.java:453)
```

I also report the function in which the error occurs in the source code `FlutterTtsPlugin.java`:
``` java
@Override
public void onStart(String utteranceId) {
     if (utteranceId != null && utteranceId.startsWith(SYNTHESIZE_TO_FILE_PREFIX)) {
          invokeMethod("synth.onStart", true);
     } else {
          Log.d(tag, "Utterance ID has started: " + utteranceId);
          invokeMethod("speak.onStart", true);
     }
     if (Build.VERSION.SDK_INT < 26) {
          // THE ERROR OCCURS IN THE LINE BELOW
          this.onProgress(utteranceId, 0, utterances.get(utteranceId).length());
     }
}
```

### Expected behavior
The voice should speak without delay.

### Reproduction steps
Simply calling the `speak` function.
**Note**: The error **does not** happen every time, only in some instances, but in different uncorrelated functions.

### Configuration
**Version:** 1.2.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by nt4f04uNd** [comment]
same, on emulator android 10
