### ISSUE TITLE
Leaked ServiceConnection in Android

### ISSUE THREAD

**Issue by luckyhandler** [dlutton/flutter_tts#148]
## 🐛 Bug Report

The Android Version leaks a Service Connection:
```
E/ActivityThread(30140): Activity my_app.app.MainActivity has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@245d6b1 that was originally bound here
E/ActivityThread(30140): android.app.ServiceConnectionLeaked: Activity my_app.app.MainActivity has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@245d6b1 that was originally bound here
E/ActivityThread(30140): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1816)
E/ActivityThread(30140): 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1688)
E/ActivityThread(30140): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1667)
E/ActivityThread(30140): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1721)
E/ActivityThread(30140): 	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
E/ActivityThread(30140): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
E/ActivityThread(30140): 	at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:821)
E/ActivityThread(30140): 	at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:772)
E/ActivityThread(30140): 	at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:744)
E/ActivityThread(30140): 	at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:723)
E/ActivityThread(30140): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.initInstance(FlutterTtsPlugin.java:55)
E/ActivityThread(30140): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.registerWith(FlutterTtsPlugin.java:46)
E/ActivityThread(30140): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:43)
E/ActivityThread(30140): 	at my_app.app.MainActivity.onCreate(MainActivity.kt:10)
E/ActivityThread(30140): 	at android.app.Activity.performCreate(Activity.java:7802)
E/ActivityThread(30140): 	at android.app.Activity.performCreate(Activity.java:7791)
E/ActivityThread(30140): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/ActivityThread(30140): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3251)
E/ActivityThread(30140): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
E/ActivityThread(30140): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/ActivityThread(30140): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/ActivityThread(30140): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/ActivityThread(30140): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
E/ActivityThread(30140): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/ActivityThread(30140): 	at android.os.Looper.loop(Looper.java:359)
E/ActivityThread(30140): 	at android.app.ActivityThread.main(ActivityThread.java:7418)
E/ActivityThread(30140): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(30140): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/ActivityThread(30140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

### Expected behavior

No leaks.

### Configuration

**Version:** ^1.2.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ryanheise** [comment]
This leak happens only with the v1 implementation due to limitations with Flutter's original plugin API. After looking into it there is potentially a half solution by hooking into `addViewDestroyListener` but the documentation for this method seems to suggest that it would only be called when the activity is destroyed and so I'm not sure if this is a universal solution that would also detect when a headless flutter view is destroyed. If it were at all worth fixing this, probably the only reliable solution would be to add another method to the API called `dispose` which cleans up these references, and then the app would need to manually call this when any Android context is about to be destroyed.

However, note that v1 is now obsolete, and this problem is not present in the v2 implementation of this plugin, so it is preferable to just upgrade your app to work with v2.

You should be able to update your project to use v2 by following the instructions here:

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by ryanheise** [comment]
By the way, Google recently updated their plugin template in two interesting ways. First, the minimum Flutter SDK version is now set to 1.20. Second, legacy v1 code has also been removed from the plugin template. What this means is that one potential solution to this bug is to simply remove the v1 implementation, now that v1 is no longer supported by Google.
