### ISSUE TITLE
Voice not working on brave browser

### ISSUE THREAD

**Issue by itsmihir** [dlutton/flutter_tts#244]
## 🐛 Bug Report

Voice if working on brave mobile browser, but not working on brave desktop browser

`main.dart.js:3757 Uncaught Invalid argument: Instance of 'minified:k8'
    at Object.a (https://cfbot.mihirkhambhati.tech/main.dart.js:3757:3)
    at Zh.d2 (https://cfbot.mihirkhambhati.tech/main.dart.js:49075:36)
    at Zl.hd (https://cfbot.mihirkhambhati.tech/main.dart.js:49163:6)
    at https://cfbot.mihirkhambhati.tech/main.dart.js:49234:29
    at a6j.a (https://cfbot.mihirkhambhati.tech/main.dart.js:5364:71)
    at a6j.$2 (https://cfbot.mihirkhambhati.tech/main.dart.js:29770:23)
    at Object.V (https://cfbot.mihirkhambhati.tech/main.dart.js:5350:19)
    at jL.X9 (https://cfbot.mihirkhambhati.tech/main.dart.js:49242:10)
    at jL.er (https://cfbot.mihirkhambhati.tech/main.dart.js:49228:34)
    at jL.cc (https://cfbot.mihirkhambhati.tech/main.dart.js:49243:32)`

This is the error shown in the console.

**Comment by dlutton** [comment]
brave is not listed as a supported browser.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
