### ISSUE TITLE
Speak() on Android sometime not speak when press two time

### ISSUE THREAD

**Issue by buingocminh** [dlutton/flutter_tts#397]
## 🐛 Bug Report

Hi I am working on a feature where users can press between 2 buttons to speak and if another is speaking, I will stop the previous and speak new word
But sometimes when speak is not complete and you press another button, it is not spoken and i get the log

```E/DartMessenger(25454): Uncaught exception in binary message listener
E/DartMessenger(25454): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger(25454): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(25454): 	at android.os.Handler.handleCallback(Handler.java:873)
E/DartMessenger(25454): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(25454): 	at android.os.Looper.loop(Looper.java:214)
E/DartMessenger(25454): 	at android.app.ActivityThread.main(ActivityThread.java:7156)
E/DartMessenger(25454): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(25454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/DartMessenger(25454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
D/TTS     (25454): Utterance ID has started: 2de2e267-a929-4cd6-a721-02cef80013b1
D/ViewRootImpl@eda076b[MainActivity](25454): ViewPostIme pointer 0
D/ViewRootImpl@eda076b[MainActivity](25454): ViewPostIme pointer 1
D/TTS     (25454): Utterance ID has been stopped: 2de2e267-a929-4cd6-a721-02cef80013b1. Interrupted: true
```
if it speak, i will get the log: 
``` E/DartMessenger(25454): Uncaught exception in binary message listener
E/DartMessenger(25454): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/DartMessenger(25454): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:278)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(25454): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(25454): 	at android.os.Handler.handleCallback(Handler.java:873)
E/DartMessenger(25454): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(25454): 	at android.os.Looper.loop(Looper.java:214)
E/DartMessenger(25454): 	at android.app.ActivityThread.main(ActivityThread.java:7156)
E/DartMessenger(25454): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(25454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/DartMessenger(25454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
D/TTS     (25454): Utterance ID has started: cd6f6323-ba5d-4da2-92f0-360f012593d1
D/ViewRootImpl@eda076b[MainActivity](25454): ViewPostIme pointer 0
D/ViewRootImpl@eda076b[MainActivity](25454): ViewPostIme pointer 1
D/TTS     (25454): Utterance ID has been stopped: cd6f6323-ba5d-4da2-92f0-360f012593d1. Interrupted: true
D/TTS     (25454): Utterance ID has started: 3611ecd7-0457-4dc7-b4d3-67e02020fc70
D/TTS     (25454): Utterance ID has completed: 3611ecd7-0457-4dc7-b4d3-67e02020fc70
```

### Reproduction steps
Here is my speak function: 
```  
void _speak() async {
    await _flutterTts.pause();
    await _flutterTts.stop();
    await _flutterTts.speak("word");
  }
```
normally this bug happened when plugin speak "word" complete but it's not complete speak() function and then you call _speak() again

**Version:** 3.7.0
sorry for the bad English, have a nice day

**Platform:** 
- [x] :robot: Android

**Comment by dlutton** [comment]
@buingocminh have you tried setting `await flutterTts.awaitSpeakCompletion(true);` first?
