### ISSUE TITLE
Speak only works the first time, probably due to Dart 2.3 upgrade

### ISSUE THREAD

**Issue by sergiuiacob1** [dlutton/flutter_tts#42]
## 🐛 Bug Report

I updated flutter to version 1.6.3 and Dart to version 2.3. Before these two, I had no problems with the `flutter_tts` package. However, after upgrading, it behaves weirdly. It speaks the first thing I throw at it, but I am receiving the error below, and after that it won't speak anything anymore.
```
W/Binder  (25778): Caught a RuntimeException from the binder stub implementation.
W/Binder  (25778): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:25778_4
W/Binder  (25778): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  (25778): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/Binder  (25778): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
W/Binder  (25778): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
W/Binder  (25778): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
W/Binder  (25778): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/Binder  (25778): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/Binder  (25778): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$1.onStart(FlutterTtsPlugin.java:42)
W/Binder  (25778): 	at android.speech.tts.TextToSpeech$Connection$1.onStart(TextToSpeech.java:2143)
W/Binder  (25778): 	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:56)
W/Binder  (25778): 	at android.os.Binder.execTransact(Binder.java:752)
W/Binder  (25778): Caught a RuntimeException from the binder stub implementation.
W/Binder  (25778): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:25778_5
W/Binder  (25778): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  (25778): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/Binder  (25778): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
W/Binder  (25778): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
W/Binder  (25778): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
W/Binder  (25778): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/Binder  (25778): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/Binder  (25778): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$1.onDone(FlutterTtsPlugin.java:47)
W/Binder  (25778): 	at android.speech.tts.TextToSpeech$Connection$1.onSuccess(TextToSpeech.java:2127)
W/Binder  (25778): 	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:64)
W/Binder  (25778): 	at android.os.Binder.execTransact(Binder.java:752)
W/IInputConnectionWrapper(25778): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(25778): getTextBeforeCursor on inactive InputConnection
```

### Reproduction steps
Here's the code I'm calling:
```
Future<void> speakText(
    BuildContext context, String language, String text) async {
  final bool result = await TTS().speak(language, text);
  if (result == false)
    showToast(AppLocalization.of(context).languageNotAvailable, "bottom");
}
```

Here is the `TTS` class I am using, I made it following the example:
```
import 'dart:async';
import 'package:flutter_tts/flutter_tts.dart';
import './models/language.dart';

enum TTSState { playing, stopped }

class TTS {
  static final TTS _singleton = TTS._internal();
  FlutterTts _flutterTts;
  TTSState _ttsState;

  factory TTS() {
    return _singleton;
  }

  TTS._internal() {
    _flutterTts = FlutterTts();
    _flutterTts.setStartHandler(() {
      _ttsState = TTSState.playing;
    });
    _flutterTts.setCompletionHandler(() {
      _ttsState = TTSState.stopped;
    });
    _flutterTts.setErrorHandler((msg) {
      _ttsState = TTSState.stopped;
    });
  }

  Future<bool> _setSpeakingLanguage(String language) async {
    String ttsAbbreviation = await getTTSLanguageAbbreviation(language);
    if (ttsAbbreviation == null) return false;
    if ((await _flutterTts.isLanguageAvailable(ttsAbbreviation)) == false)
      return false;
    _flutterTts.setLanguage(ttsAbbreviation);
    return true;
  }

  Future<String> getTTSLanguageAbbreviation(String language) async {
    String googleTranslateAbbreviation = allLanguages.keys
        .toList()[allLanguages.values.toList().indexOf(language)];
    List ttsLanguages = await _flutterTts.getLanguages;
    if (ttsLanguages == null) return null;
    List filtered = ttsLanguages
        .where((item) => item.startsWith(googleTranslateAbbreviation))
        .toList();
    if (filtered == null) return null;
    if (filtered.length == 0) return null;

    if (filtered.length > 1) {
      List doubleFiltered = filtered
          .where((item) =>
              item.toLowerCase().endsWith(googleTranslateAbbreviation))
          .toList();
      if (doubleFiltered.length > 0) return doubleFiltered.first as String;
    }

    return filtered.first as String;
  }

  Future<bool> speak(String language, String text) async {
    if (_ttsState == TTSState.playing) return true;
    if (await _setSpeakingLanguage(language) == false) return false;

    var result = await _flutterTts.speak(text);
    if (result == 1) _ttsState = TTSState.playing;
    return true;
  }

  Future<void> stop() async {
    var result = await _flutterTts.stop();
    if (result == 1) _ttsState = TTSState.stopped;
  }

  void dispose() {
    _flutterTts.stop();
  }

  get isPlaying => _ttsState == TTSState.playing;
  get isStopped => _ttsState == TTSState.stopped;
}
```
### Configuration
Flutter 1.6.3, Dart 2.3, flutter_tts 0.2.4

**Platform:** 
Only tested it on Android, as I can't run iOS yet due to some different issues.

**Comment by dlutton** [comment]
I tested the example in this repo using Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5) on their stable channel v1.5.4-hotfix.2 and I'm unable to recreate the issue.  However there is a PR to fix the error in your stack trace, so I'm hoping that will fix it once I push the change.

**Comment by sergiuiacob1** [comment]
So probably a fix would be to switch to the stable channel, as I'm on the beta channel (v 1.6.3). Can you link that pull request here, please?

**Comment by dlutton** [comment]
I have merged the PR so you can test now.

**Comment by sergiuiacob1** [comment]
Alright! It works just fine now, so I'll consider this solved :)
I'm receiving a feedback message when I call the `speak()` function, in case it matters:
`D/OnePlusJankManager(13716):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.sergiuiacob.words.debug/com.sergiuiacob.words.MainActivity--- jank level = 1`
But that is by no means an error, just an informative message.
Thank you for your hasty fix! Hugs and kisses, good job with the plugin! :)
