### ISSUE TITLE
synthesizeToFile broken on Android

### ISSUE THREAD

**Issue by mchlsndrn** [dlutton/flutter_tts#443]
🐛 Bug Report

**synthesizeToFile() not working on Android.**

Please correct me if I'm wrong but I think that, on **Android**, flutter_tts still tries to write in
getExternalStorageDirectory() // in Android
instead of 
getApplicationDocumentsDirectory() // in iOS

Besides the fact that the behavior is inconsistent, it's also a problem because the filesystem permission system was changed some time ago.
https://developer.android.com/about/versions/11/privacy/storage

### Reproduction steps
```
await flutterTts.awaitSynthCompletion(true);
await flutterTts.synthesizeToFile(ttsController.text, "tts.wav");

E/TextToSpeech(22332): Opening file tts.wav failed
E/TextToSpeech(22332): java.io.FileNotFoundException: open failed: EROFS (Read-only file system)
E/TextToSpeech(22332): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:342)
E/TextToSpeech(22332): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:229)
E/TextToSpeech(22332): 	at android.speech.tts.TextToSpeech.synthesizeToFile(TextToSpeech.java:1899)
E/TextToSpeech(22332): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.synthesizeToFile(FlutterTtsPlugin.kt:627)
E/TextToSpeech(22332): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.kt:320)
E/TextToSpeech(22332): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/TextToSpeech(22332): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/TextToSpeech(22332): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/TextToSpeech(22332): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/TextToSpeech(22332): 	at android.os.Handler.handleCallback(Handler.java:942)
E/TextToSpeech(22332): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/TextToSpeech(22332): 	at android.os.Looper.loopOnce(Looper.java:201)
E/TextToSpeech(22332): 	at android.os.Looper.loop(Looper.java:288)
E/TextToSpeech(22332): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/TextToSpeech(22332): 	at java.lang.reflect.Method.invoke(Native Method)
E/TextToSpeech(22332): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/TextToSpeech(22332): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/TTS     (22332): Failed creating file : tts.wav
```

**Version:** 3.8.5

**Comment by mchlsndrn** [comment]
Here's another user in SO with the same issue.
https://stackoverflow.com/questions/77580996/sythesize-to-file-not-working-properly-fluttertts

**Comment by mchlsndrn** [comment]
Allright, so apparently you can provide "synthesizeToFile" with a path that begins like "$applicationDocumentsDirectory/$basename.$extension" and synthesizeToFile will respect it, at least on android.

**Comment by mchlsndrn** [comment]
(this doesn't change the fact that the default behavior still raises an exception though).
