### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by meowofficial** [dlutton/flutter_tts#472]
## 🐛 Bug Report

I got this exception in Crashlytics:

```
java.lang.NullPointerException: null
    at com.tundralabs.fluttertts.FlutterTtsPlugin.onInitListener$lambda$3(FlutterTtsPlugin.kt:229)
    at com.tundralabs.fluttertts.FlutterTtsPlugin.$r8$lambda$XaP8S28PtXzgWQDslTYZpfp1vzk
    at com.tundralabs.fluttertts.FlutterTtsPlugin$$ExternalSyntheticLambda1.onInit
    at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:824)
    at android.speech.tts.TextToSpeech.-wrap4
    at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2221)
    at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2214)
    at android.os.AsyncTask.finish(AsyncTask.java:727)
    at android.os.AsyncTask.-wrap1
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Device: AUM-L41
Android version: 8.0.0 
Package version: 4.0.1

**Comment by dlutton** [comment]
@meowofficial unfortunately I'm not familiar with that device, are you able to recreate the issue?

**Comment by meowofficial** [comment]
@dlutton No, I have only Google Pixel and there is no such an issue. I hope attached stacktrace may help you figure out what could go wrong.

**Comment by htbeazxcq123** [comment]
got the same exception and crushed
