### ISSUE TITLE
Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference

### ISSUE THREAD

**Issue by meowofficial** [dlutton/flutter_tts#477]
## 🐛 Bug Report

Stack Trace:

```
PlatformException: PlatformException(error, Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference
	at com.tundralabs.fluttertts.FlutterTtsPlugin.setVoice(FlutterTtsPlugin.kt:495)
	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.kt:407)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
)
  File "message_codecs.dart", line 651, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 334, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "flutter_tts.dart", line 465, in FlutterTts.setVoice
```
The error is occurring only after an attempt to set voice.

<details>
  <summary>Some information about devices</summary>
  
<img width="317" alt="Снимок экрана 2024-03-26 в 17 54 14" src="https://github.com/dlutton/flutter_tts/assets/35203503/07fcd004-cd41-4b72-bae7-04d0c57db23f">

</details>

As far as I understand there is no need to wait for `onInit` anymore per #81 as you suggested in #73.

Maybe related: #139 #73 

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by AhmadKhateeb-quizplus** [comment]
+1
