### ISSUE TITLE
getDefaultVoice method throws an Exception

### ISSUE THREAD

**Issue by ihr1337** [dlutton/flutter_tts#501]
## 🐛 Bug Report

When getDefaultVoice method is invoked - I get an Exception

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getDefaultVoice on channel flutter_tts)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      FlutterTts.getDefaultVoice (package:flutter_tts/flutter_tts.dart:502:19)`

**Version:** 4.0.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by zeqinjie** [comment]
yes me too, look like https://github.com/flutter/flutter/issues/16049 ?
