### ISSUE TITLE
Flutter tts initialization causing crashes in android app 

### ISSUE THREAD

**Issue by alihassan143** [dlutton/flutter_tts#554]
## 🐛 Bug Report

```
Exception java.lang.NullPointerException:
  at com.tundralabs.fluttertts.FlutterTtsPlugin.onInitListener$lambda$3 (FlutterTtsPlugin.kt:240)
  at com.tundralabs.fluttertts.FlutterTtsPlugin.$r8$lambda$XaP8S28PtXzgWQDslTYZpfp1vzk (Unknown Source)
  at com.tundralabs.fluttertts.FlutterTtsPlugin$$ExternalSyntheticLambda2.onInit (Unknown Source:2)
  at android.speech.tts.TextToSpeech.dispatchOnInit (TextToSpeech.java:824)
  at android.speech.tts.TextToSpeech.-wrap4 (Unknown Source)
  at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute (TextToSpeech.java:2221)
  at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute (TextToSpeech.java:2214)
  at android.os.AsyncTask.finish (AsyncTask.java:727)
  at android.os.AsyncTask.-wrap1 (Unknown Source)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:744)
  at android.os.Handler.dispatchMessage (Handler.java:109)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7555)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
```

**Version:** 4.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by hsangtini** [comment]
E/AndroidRuntime( 5356): java.lang.NullPointerException
E/AndroidRuntime( 5356): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onInitListener$lambda$3(FlutterTtsPlugin.kt:240)
E/AndroidRuntime( 5356): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.$r8$lambda$XaP8S28PtXzgWQDslTYZpfp1vzk(Unknown Source:0)
E/AndroidRuntime( 5356): 	at com.tundralabs.fluttertts.FlutterTtsPlugin$$ExternalSyntheticLambda2.onInit(Unknown Source:2)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$android-speech-tts-TextToSpeech(TextToSpeech.java:890)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech.-$$Nest$mdispatchOnInit(Unknown Source:0)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
E/AndroidRuntime( 5356): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
E/AndroidRuntime( 5356): 	at android.os.AsyncTask.finish(AsyncTask.java:771)
E/AndroidRuntime( 5356): 	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
E/AndroidRuntime( 5356): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
E/AndroidRuntime( 5356): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5356): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 5356): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 5356): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime( 5356): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5356): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime( 5356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by dlutton** [comment]
fixed in latest version
