### ISSUE TITLE
Failed when build aar

### ISSUE THREAD

**Issue by susilon** [dlutton/flutter_tts#61]
There was no problem with "flutter build apk" command,
but when I try to build into AAR ("flutter build aar", yes it still an experiment), build failed.

OS : Windows
Flutter channels : master, v1.10.6-pre.39
Android SDK : 28.0.3

```
[   +1 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[   +1 ms] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 390
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred configuring root project 'android_generated'.
[   +1 ms] > A problem occurred configuring project ':flutter'.
[        ]    > Could not find method execute() for arguments [] on task ':flutter:buildPluginReleaseFlutterTts' of typeFlutterPluginTask.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +602 ms] Running Gradle task 'assembleAarRelease'... (completed in 2.1s)
[   +5 ms] "flutter aar" took 10,930ms.
Gradle task assembleAarRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:658:5)
<asynchronous suspension>
#2      _AndroidBuilderImpl.buildAar (package:flutter_tools/src/android/android_builder.dart:73:11)
<asynchronous suspension>
#3      BuildAarCommand.runCommand (package:flutter_tools/src/commands/build_aar.dart:67:26)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:444:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:434:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1500:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:62:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:50:10)
#40     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#41     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by dlutton** [comment]
What gradle version are you using?

**Comment by susilon** [comment]
My Gradle version is 3.5.0, thank you

**Comment by dlutton** [comment]
Have you tried with version 3.2.1? I haven't tried aar myself, but after going through some of the issues mentioned in github, it could be related to the distributionURL value I'm using in gradle-wrapper.properties or the gradle version.  You could try forking this project and updating the distributionURL to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip` which is located at: android/gradle/wrapper/gradle-wrapper.properties.

**Comment by susilon** [comment]
Yes it works now,
Thank you.
