### ISSUE TITLE
unable to play in "en-GB"

### ISSUE THREAD

**Issue by caduandrade** [dlutton/flutter_tts#65]
Before I have to say: amazing API, congratulations.

I can't play using "en-GB" as language. "en-US" works fine.

```
    _flutterTts.setErrorHandler((msg) {
      print("tts error: " + msg);
    });
    String language = "en-GB";
    String text = "test";
    print(await _flutterTts.isLanguageAvailable(language));
    await _flutterTts.setLanguage(language);
    await _flutterTts.speak(text);
```

Result:

> I/flutter ( 5395): true
> I/flutter ( 5395): tts error: Error from TextToSpeech

Mobile: Android - Motorola G6 Plus

flutter_tts versions: 0.5.2 or 0.6.0

build.gradle:

> minSdkVersion 21
> targetSdkVersion 28

PS.: TTS in my other Android pure app works fine with "en-GB"

**Comment by caduandrade** [comment]
Looking your source code (FlutterTtsPlugin), I expected to receive the errorCode in the error message.

```
                @Override
                @Deprecated
                public void onError(String utteranceId) {
                    invokeMethod("speak.onError", "Error from TextToSpeech");
                }

                @Override
                public void onError(String utteranceId, int errorCode) {
                    invokeMethod("speak.onError", "Error from TextToSpeech - " + errorCode);
                }
```

the first onError has been deprecated on API 21 but is still being called :-(

**Comment by dlutton** [comment]
@caduandrade I haven't had any issues with TTS using "en-GB".  What's the API level of your Motorola G6 Plus?  I have tested using the example in this package on API level 28.

**Comment by caduandrade** [comment]
Motorola G6 Plus is 28 as well. 

Sorry... I just back to my pure Android  app and now the "en-GB" language is also having the same problem! It always worked. It's some problem with my phone. Sorry for the fake bug and your time.

**Comment by caduandrade** [comment]
Just out of curiosity, I get this error on my android app:

> 2019-10-02 14:52:48.046 5539-6016/? I/TTS.GoogleTTSServiceImp: For default lang en-gb is name en-GB-language (en-gb-x-fis-server)
> 2019-10-02 14:52:48.049 5539-11612/? W/TTS.Dispatcher: No network voice found, will fall back to local immediately
> 2019-10-02 14:52:48.050 5539-11612/? I/TTS.ControllerWrapper: Initializing en-gb-x-fis-lstm-embedded from disk
> 2019-10-02 14:52:48.052 5539-11612/? E/TTS.ControllerWrapper: Unable to open project file.
>     java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/en-gb/en-gb-x-fis-r10/pipeline (No such file or directory)
>         at java.io.FileInputStream.open0(Native Method)
>         at java.io.FileInputStream.open(FileInputStream.java:231)
>         at java.io.FileInputStream.<init>(FileInputStream.java:165)
>         at java.io.FileInputStream.<init>(FileInputStream.java:112)
>         at bxs.a(PG:162)
>         at bxs.b(PG:174)
>         at bxs.a(PG:200)
>         at bxt.b(PG:151)
>         at bxt.a(PG:7)
>         at com.google.android.tts.service.GoogleTTSService.onLoadVoice(PG:351)
>         at android.speech.tts.TextToSpeechService$LoadVoiceItem.playImpl(TextToSpeechService.java:1250)
>         at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
>         at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
> 2019-10-02 14:52:48.053 5539-11612/? E/TTS.LocalSynthesizer: Failed initializing controller with voice en-gb-x-fis-lstm-embedded

**Comment by dlutton** [comment]
I'm not sure @caduandrade, do you have additional context to this issue such as what the app is trying to do while you encounter this error message?

**Comment by caduandrade** [comment]
No. Only trying to play the TTS.
In my case, it looks like the voice file is corrupted on my phone.
Tks!

**Comment by nanox77** [comment]
I have same issue when execute `flutterTts.speak(...)` using `^0.6.0` version:

```
--
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/es-us/es-us-x-sfb-r8/pipeline (No such file or directory)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at java.io.FileInputStream.open(Native Method)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at bxs.a(PG:162)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at bxs.b(PG:174)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at bxs.a(PG:200)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at bxt.b(PG:151)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at bxt.a(PG:10)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at com.google.android.tts.service.GoogleTTSService.onSynthesizeText(PG:212)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at android.speech.tts.TextToSpeechService$SynthesisSpeechItemV1.playImpl(TextToSpeechService.java:991)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:793)
10-13 10:02:18.617 23550 26307 E TTS.ControllerWrapper: 	at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:567)
--
```

@caduandrade How did you solve your issue?

Thank you!

**Comment by caduandrade** [comment]
@nanox77 

I didn't yet. I'm with same problem in a pure Android app. I don't know how but the voice file has been deleted or corrupted.

**Comment by nanox77** [comment]
I tried with [this example ](https://github.com/dlutton/flutter_tts/blob/master/example/lib/main.dart) and when I selected from dropdown menu doesn't work with `es-US` and `es-ES` languages. Here is example:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

enum TtsState { playing, stopped }

class _MyAppState extends State<MyApp> {
  FlutterTts flutterTts;
  dynamic languages;
  dynamic voices;
  String language;
  String voice;
  int silencems;

  String _newVoiceText;

  TtsState ttsState = TtsState.stopped;

  bool get isPlaying => ttsState == TtsState.playing;

  bool get isStopped => ttsState == TtsState.stopped;

  @override
  void initState() {
    super.initState();
    initTts();
  }

  void initTts() {
    flutterTts = FlutterTts();

    flutterTts.getLanguages.then((dynamic valuesLangs) {
      setState(() {
        languages = valuesLangs;
      });
    });
    flutterTts.setStartHandler(() {
      setState(() {
        ttsState = TtsState.playing;
      });
    });

    flutterTts.setCompletionHandler(() {
      setState(() {
        print("Complete");
        ttsState = TtsState.stopped;
      });
    });

    flutterTts.setErrorHandler((dynamic msg) {
      setState(() {
        ttsState = TtsState.stopped;
      });
    });
  }

  Future _speak() async {
    if (_newVoiceText != null) {
      if (_newVoiceText.isNotEmpty) {
        dynamic result = await flutterTts.speak(_newVoiceText);
        if (result == 1) setState(() => ttsState = TtsState.playing);
      }
    }
  }

  Future _stop() async {
    dynamic result = await flutterTts.stop();
    if (result == 1) setState(() => ttsState = TtsState.stopped);
  }

  @override
  void dispose() {
    super.dispose();
    flutterTts.stop();
  }

  List<DropdownMenuItem<String>> getLanguageDropDownMenuItems() {
    var items = List<DropdownMenuItem<String>>();
    for (String type in languages) {
      items.add(DropdownMenuItem(value: type, child: Text(type)));
    }
    return items;
  }

  List<DropdownMenuItem<String>> getVoiceDropDownMenuItems() {
    var items = List<DropdownMenuItem<String>>();
    for (String type in voices) {
      items.add(DropdownMenuItem(value: type, child: Text(type)));
    }
    return items;
  }

  void changedLanguageDropDownItem(String selectedType) {
    setState(() {
      language = selectedType;
      flutterTts.setLanguage(language);
    });
  }

  void _onChange(String text) {
    setState(() {
      _newVoiceText = text;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter TTS'),
        ),
        body: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Column(
            children: [
              inputSection(),
              btnSection(),
              languages != null ? languageDropDownSection() : Text(""),
            ],
          ),
        ),
      ),
    );
  }

  Widget inputSection() => Container(
        alignment: Alignment.topCenter,
        padding: EdgeInsets.only(top: 25.0, left: 25.0, right: 25.0),
        child: TextField(
          onChanged: (String value) => _onChange(value),
        ),
      );

  Widget btnSection() => Container(
        padding: EdgeInsets.only(top: 50.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            _buildButtonColumn(Colors.green, Colors.greenAccent, Icons.play_arrow, 'PLAY', _speak),
            _buildButtonColumn(Colors.red, Colors.redAccent, Icons.stop, 'STOP', _stop)
          ],
        ),
      );

  Widget languageDropDownSection() => Container(
        padding: EdgeInsets.only(top: 50.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            DropdownButton(
              value: language,
              items: getLanguageDropDownMenuItems(),
              onChanged: changedLanguageDropDownItem,
            )
          ],
        ),
      );

  Column _buildButtonColumn(Color color, Color splashColor, IconData icon, String label, Function func) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        IconButton(icon: Icon(icon), color: color, splashColor: splashColor, onPressed: () => func()),
        Container(
          margin: const EdgeInsets.only(top: 8.0),
          child: Text(
            label,
            style: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400, color: color),
          ),
        ),
      ],
    );
  }
}

```

And here is `flutter doctor -v`:
```
flutter doctor -v 
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-AR)
    • Flutter version 1.9.1+hotfix.4 at /Users/user/Documents/Flutter/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • XT1575 • TA08403NK0 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

@dlutton Do you have any idea what the problem is?. Thank you!!

**Comment by nanox77** [comment]
I 'solved' the problem. I had to disable `Google Text-to-speech Engine` from my phone and enable and then download languages again.
It's weird because it has previously worked.

**Comment by caduandrade** [comment]
@nanox77 good trick. 
Same with me. It was working before. 
I just deleted the voice and choose to download again. Now its working as well. Maybe I will show this trick if a failure occurs.

**Comment by nanox77** [comment]
@caduandrade It's weird, my only concern is if this happens to the end user. I don't find a way to fix this problem programmatically yet.

**Comment by caduandrade** [comment]
@nanox77 yeah, it's bad. It's possible use an Intent to install data voice in Android when the language is not available (TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA). But it's not what happened with us. The language was available.

**Comment by VigneshPasupathy** [comment]
This issue seems to be happening quite often across our different testing devices.  The delete voice file and download did work but is there any specific reason why this happens?

**Comment by jan-koz** [comment]
Any updates on this? Recently came across this problem

**Comment by dlutton** [comment]
@jan-koz I'll need to dig into this issue as I don't have a solution for it yet.

**Comment by hasanm08** [comment]
I have the same issue on motorala phones
they have delays on play sound
I wounder that can this helps or not?
```
  if (!AppUtils.isWeb && Platform.isAndroid) {
      await flutterTts.setSilence(0); //Android only
    }
```
