### ISSUE TITLE
How to build for IOS

### ISSUE THREAD

**Issue by xm0128** [dlutton/flutter_tts#69]
I am running:
Xcode Version 11.1 (11A1027)
Flutter Version 1.10.15-pre.168

After getting this error:
    _

> Downloading dependencies
>     -> Using Flutter (1.0.0)
>     -> Using flutter_tts (0.0.1)
>       - Running pre install hooks
>     [!] Unable to determine Swift version for the following pods:
>     - `flutter_tts` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:590:in `validate_targets'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:158:in `install!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command/install.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> Error output from CocoaPods:
> ↳
>         WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
>         Consider adding the following to ~/.profile:
>         export LANG=en_US.UTF-8
>         
>     [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> Error output from Xcode build:
> ↳

I added this 
ENV['SWIFT_VERSION'] = '5.0'
in my Podfile.

Then I get this Error:

> Xcode's output:
> ↳
>     /Users/rap13038/Develop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.6.0/ios/Classes/SwiftFlutterTtsPlugin.swift:24:55: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
>           try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
>                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                           AVAudioSession.Category.playback
>     AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
>     public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
>                ^
>     note: Using new build systemnote: Planning buildnote: Constructing build description
> Could not build the application for the simulator.
> Error launching application on iPhone 11 Pro Max.## 💬 Questions and Help
> 
> Provide question related to this flutter plugin.
> 
> 

What am I doing wrong?

**Comment by dlutton** [comment]
You're not doing anything wrong.  This is related to issue #25 .

**Comment by xm0128** [comment]
> You're not doing anything wrong. This is related to issue #25 .

Thanks. Quick response. Nice!
