### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by Dorbmon** [dlutton/flutter_tts#88]
When I try to speak something,an error came out although it exactly worked.
This is my error report:
```
E/MethodChannel#flutter_tts( 7325): Failed to handle method call
E/MethodChannel#flutter_tts( 7325): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter_tts( 7325): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/MethodChannel#flutter_tts( 7325): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:241)
E/MethodChannel#flutter_tts( 7325): 	at com.tundralabs.fluttertts.FlutterTtsPlugin.onMethodCall(FlutterTtsPlugin.java:176)
E/MethodChannel#flutter_tts( 7325): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_tts( 7325): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_tts( 7325): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_tts( 7325): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_tts( 7325): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter_tts( 7325): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter_tts( 7325): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/MethodChannel#flutter_tts( 7325): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_tts( 7325): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter_tts( 7325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/DartMessenger( 7325): Uncaught exception in binary message listener
E/DartMessenger( 7325): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger( 7325): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/DartMessenger( 7325): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:246)
E/DartMessenger( 7325): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger( 7325): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/DartMessenger( 7325): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger( 7325): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/DartMessenger( 7325): 	at android.os.Looper.loop(Looper.java:173)
E/DartMessenger( 7325): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/DartMessenger( 7325): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 7325): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/DartMessenger( 7325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

This is my flutter doctor -v:

```
[√] Flutter (Channel master, v1.16.2-pre.21, on Microsoft Windows [Version
    10.0.18363.720], locale zh-CN)
    • Flutter version 1.16.2-pre.21 at E:\flutter
    • Framework revision bee45a646f (13 hours ago), 2020-03-19 21:26:01 -0400
    • Engine revision 046a4a6c2b
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 5b21a43c55)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dorbmon\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    • All Android licenses accepted.
```

It is a example to make the bug apear:
```
import 'package:flutter/material.dart';
import 'package:flutter_tts/flutter_tts.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FlutterTts flutterTts;
  @override
  void initState() {
    super.initState();
    flutterTts = FlutterTts ();
    flutterTts.speak("Hello World");
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
          ],
        ),
      ),
    );
  }
}

```

**Comment by thevikke** [comment]
I have the same error, I experimented a bit and it feels like it works some times and sometimes not, depending on the text that I input.

**Comment by dlutton** [comment]
thanks @thevikke, I'll try to make some time this weekend to look into the issue.

**Comment by Dorbmon** [comment]
> 我遇到了同样的错误，我做了一些实验，感觉它有时会起作用，有时却不起作用，这取决于我输入的文本。
> 
> ---编辑---
> 是的，我是个笨蛋，在tts的Android API中明确设置了4000个字符的限制。但是，错误消息仍显示为<4000个字符的文本。

Howerver,Mine is different haha.I only want to say "Hello World".

**Comment by Dorbmon** [comment]
> I have the same error, I experimented a bit and it feels like it works some times and sometimes not, depending on the text that I input.
> 
> ---Edit---
> Yes, I'm a moron, the limit 4000 characters is clearly set in the Android API of tts. However, the error message still shows with < 4000 character text.

However My word is only "Hello World" haha.

**Comment by dlutton** [comment]
thanks for reporting this @Dorbmon and @thevikke.  This should now be resolved.

**Comment by verybox0** [comment]
I still have such error, but, only when I navigate back to main screen, so, the child screen has TTS, but, not in Main screen, it uses Navigator.push(context, MaterialPageRoute) to jump from Main=>Child.

**Comment by dlutton** [comment]
@verybox0 is TTS being instantiated each time a user navigates back?

**Comment by JohnF17** [comment]
Hey @dlutton, I've been experiencing this issue myself and rather than creating a new issue , I'll just mention here that I've found the problem. Calling the stop method when TTS is not playing throws an uncaught exception!
Caused by this below

```kt
private fun stop() {
    if (awaitSynthCompletion) synth = false
    if (awaitSpeakCompletion) speaking = false
    tts!!.stop() // This
 }
```

Maybe changing it to this below might be best
```kt
private fun stop() {
  if (awaitSynthCompletion) synth = false 
  if (speaking) {
      tts!!.stop() // Or tts?.stop()
  }
  if (awaitSpeakCompletion) speaking = false
}
```
Or a try-catch method.

And as for dart users that experience this, till a new update is released, all you can do is check if tts is playing before calling stop.
I ran into this issue when stopping the TTS before going back to a previous page, just as [this comment](https://github.com/dlutton/flutter_tts/issues/88#issuecomment-1403020513) described.
Cheers 👍
